### PR TITLE
Updated build process

### PR DESCRIPTION
**Pull request by LaurensRietveld**
Hi there,

I wanted to try your project but had some problems building it. 
So I modified the build process a bit, noticably:
- use tsconfig for storing all typescript related settings
- added some missing type defs
- use gulp to build the ts files
- added post-install script to re-transpile ts when the package is installed (i.e., committing the dist directory could be ignored)
- added source map support to get ts stacktraces

### CODE REVIEW

**Comment by Zir01** [comment]
Hi Laurens
Looks like you have deleted gulpfile.ts and edited the gulpfile.js file directly. I am using VS as my IDE which automatically builds the project on save of .ts files, this is the reason no build task in the gruntfile. I am assuming you are using a different IDE. The omission of the gulpfile.ts file breaks my setup within VS. Is it possible for you to keep gruntfile.ts and move your "build" task within the gulpfile.ts and then configure your IDE to build gulpfile.ts ==> gulpfile.js so we can both work in different environments.

Thanks for trying this project out. I haven't worked on it for some time as it does all I need at the moment and still using it in my dev environment (mainly use it to auto create client code plumbing to interface with web api).

**Comment by LaurensRietveld** [comment]
Hi there, 

Jup, I'm using atom on linux. I'll make some updates to make us both happy

**Comment by Zir01** [comment]
Legend!
I thought so. I reckon that minor change will do it

**Comment by LaurensRietveld** [comment]
I've reverted back to a ts gulpfile. Could you check whether your setup still works?

**Comment by Zir01** [comment]
I am out of office, I'll have to get back to you.

**Comment by Zir01** [comment]
Sorry it took me so long to merge but was occupied with other things. Thanks

**Pull request merged**
